function [eps] = defineEpochNimbusShoesTesting_Session2(nantype)


names={'OGBase','OGbaseNimbus','TMslow','TMmid','TMfast',...
    'NegPlus','OGafterNegPlus','TMfast2','PostShort',...
    'OGAfterPost','TMslow2','NegShort','OGAfterNeg','TMfast3','ShortSplit','OGAfterShortSplit'};


eps=defineEpochs(names,...
                {'OG base','OG nimbus','TM slow base','TM mid','TM fast 2',...
                'Neg plus delta','OG after neg plus','TM tied 2','Pos short',...
                'OG 2','TM slow','Neg short','OG 3','TM fast','Short split','OG 1'},...
                [-40 -40 -40 -40 -40,...
                    20 20 -40 20,...
                    20 -40 20 20 -40 20 20],...
                [0,0,0,0,0,...
                    1,1,0,1,...
                    1,0,1,1,0,1,1],...
                [5,5,5,5,5,...
                    0,0,5,0,...
                    0,5,0,0,5,0,0],...
                nantype);
