function [eps] = defineEpochVR_OG_UpdateV3(nantype)


names={'Env_{Switch}','TMBaseNOVR','Adapt (\DeltaEMG_{on(-)})','SplitPos','TRbase','TMbase',...
    'Task_{Switch}','OGpost-Adapt_{SS}','OGpost_{Early}','OGpost_{Late}','TMPost_{Early}','TMPost_{Late}', 'NonAdapt (-\DeltaEMG_{on(+)})'};

eps=defineEpochs(names,...
                {'OG base','TM tied 1','Neg Short','Pos Short','TR base','TM tied 1','Adaptation',...
                'Post 1','Post 1','Post 1','Post 2','Post 2','TM tied 1'},...
                [-40 -40 20 20 -40 -40 -40 20 20 -40 20 -40 -40],...
                [0,0,1,1,0,0,0,1,1,0,1,0,0],...
                [5,5,0,0,5,5,5,0,0,5,0,5,5],...
                nantype);