function [eps] = defineEpocNimbusShoes(nantype)

% names={'Base', 'EarlyA', 'LateA' ,'EarlyP', 'LateP'};

names={'BaseNoShoes','TMBaseShoes','SplitPos','SplitNeg','OGNimbus','Adaptation','EMGss-post','OGpostEarly','OGpostLate','WashoutEarly','WashoutLate'};

eps=defineEpochs(names,...
                {'OG base: no Nimbus','TM Nimbus: Nimbus off 3','Short Split +','Short Split -','OG nimbus: Nimbus off','Adaptation','OG post: No nimbus','OG post: No nimbus','OG post: No nimbus','Washout: Nimbus off','Washout: Nimbus off'},...
                [-40 -40 20 20 -40 -40 20 20 -40 20 -40],...
                [0,0,1,1,0,0,1,1,0,1,0],...
                [40,5,0,0,5,5,0,0,5,0,5],...
                nantype);