function [eps] = defineEpochNimbusShoes(nantype)

% names={'Base', 'EarlyA', 'LateA' ,'EarlyP', 'LateP'};

names={'BaseNoShoes','TMBaseShoes','SplitNeg','SplitPos','OGNimbus','Adaptation','Post1-Adapt_{SS}','Post1_{Early}','Post1_{Late}','Post2_{Early}','Post2_{Late}'};

eps=defineEpochs(names,...
                {'OG base','TM base','Neg Short','Pos Short','NIM Base','Adaptation','Post 1','Post 1','Post 1','Post 2','Post 2'},...
                [-40 -40 20 20 -40 -40 20 20 -40 20 -40],...
                [0,0,1,1,0,0,1,1,0,1,0],...
                [40,5,0,0,5,5,0,0,5,0,5],...
                nantype);