function [eps] = defineEpochNimbusShoesTesting_Session2(nantype)

% names={'Base', 'EarlyA', 'LateA' ,'EarlyP', 'LateP'};

names={'OGBase','OGbaseNimbus','TMslow','TMmid','TMfast',...
    'NegPlus','OGafterNegPlus','TMfast2','PostShort',...
    'OGAfterPost','TMslow2','NegShort','OGAfterNeg','TMfast3','ShortSplit','OGAfterShortSplit'};

% if strcmp(subjID, 'NTR_02')
%     exemptFirstShortSplit = 23;
% elseif strcmp(subjID, 'NTR_03')
%     exemptFirstShortSplit = 24;
% elseif strcmp(subjID, 'NTR_04')
%     exemptFirstShortSplit = 17;  


eps=defineEpochs(names,...
                {'OG base','OG nimbus','TM slow base','TM mid','TM fast 2',...
                'Neg plus delta','OG after neg plus','TM tied 2','Pos short',...
                'OG2','TM slow','Neg short','OG3','TM fast','Short split','OG1'},...
                [-40 -40 -40 -40 -40,...
                    20 20 -40 20,...
                    20 -40 20 20 -40 20 20],...
                [0,0,0,0,0,...
                    1,1,0,1,...
                    1,0,1,1,0,1,1],...
                [5,5,5,5,5,...
                    0,0,5,0,...
                    0,5,0,0,5,0,0],...
                nantype);
%             Temp change,  during short split for NTR02, ignore first 23
%             strides (bad strides), use 20 strides, exempt first 23 (the #
%             of strides do not include the exempted strides)
%             Temp change,  during short split for NTR03, ignore first 24 strides (bad strides)