function [eps] = defineEpochNIM_OG_UpdateV1_flipSign(nantype)


names={'OGbase','TMbase','\DeltaEMG_{on(-)}','SplitPos','Env_{Switch}','NIMBase',...
   'Task_{Switch}','Post1-Adapt_{SS}','Post1_{Early}','Post1_{Late}','Post2_{Early} - Post1_{Late}','Post2_{Late}','NIM Base'};

eps=defineEpochs(names,...
                {'OG Base','TM Base','Neg Short','Pos Short','NIM Base','NIM Base'...
                'Adaptation','Post 1','Post 1','Post 1','Post 2','Post 2','NIM Base'},...
                [-40 -40 20 20 -40 -40 -40 20 20 -40 20 -40 -40],...
                [0,0,1,1,0,0,0,1,1,0,1,0, 0 ],...
                [5,5,0,0,5,5,5,0,0,5,0,5, 5],...
                nantype);
   