function [eps] = defineEpocNimbusShoesRegressor(nantype)

% names={'Base', 'EarlyA', 'LateA' ,'EarlyP', 'LateP'};

names={'TMBaseShoes','-EMG_{on(+)}','SplitPos','EMG_{on(-)}','OGNimbus','Adaptation','OGpost-Adapt_{SS}','OGpostEarly'};

eps=defineEpochs(names,...
                {'TM Nimbus: Nimbus off 3','TM Nimbus: Nimbus off 3','Short Split +','Short Split -',...
                'OG nimbus: Nimbus off','Adaptation','OG post: No nimbus','OG post: No nimbus'},...
                [-40 -40 20 20 -40  -40 20 20],...
                [0 0,1,1,0,0,1,0],...
                [5,5,0,0,5,5,0,5],...
                nantype);