function [eps] = defineEpocVR_OG_Regressor(nantype)

names={'TMbase','-\DeltaEMG_{on(+)}','SplitPos','\DeltaEMG_{on(-)}','OGbase','\DeltaEMG_{ss}','Adaptation','OGpost-Adapt_{SS}','OGpostEarly'};

eps=defineEpochs(names,...
                {'TM base','TM base','Pos Short','Neg Short',...
                'OG Base','OG Base','Adaptation','OG post','OG post'},...
                [-40 -40 20 20 -40 -40  -40 20 20],...
                [0 0,1,1,0,0,0,1,0],...
                [5,5,0,0,5,5,5,0,5],...
                nantype);
            
   