function [eps] = defineEpochVR_OG_UpdateV4(nantype)

% Version change: use pos/neg short 1 to represent short perturbation, and
% short perturbations are normalized by TM slow instead of TM tied 1
% 
% 

names={'-MultiEnvSwitch','TMBaseNOVR','Adapt (\DeltaEMG_{on(-)})2','SplitPos','TRbase','TMbase',...
    'Task_{Switch}','Post1-Adapt_{SS}','Post1_{Early}','Post1_{Late}','Post2_{e}-Post1_{l}','Post2_{Late}', 'WithinEnvSwitch (-\DeltaEMG_{on(+)})2'};

eps=defineEpochs(names,...
                {'OG base','TM tied 4','Neg Short 1','Pos Short 1','TR base','TM tied 4','Adaptation',...
                'Post 1','Post 1','Post 1','Post 2','Post 2','TM tied 4'},...
                [-40 -40 20 20 -40 -40 -40 20 20 -40 20 -40 -40],...
                [0,0,1,1,0,0,0,1,1,0,1,0,0],...
                [5,5,0,0,5,5,5,0,0,5,0,5,5],...
                nantype);