function [eps] = defineEpocNimbusShoes(nantype)

% names={'Base', 'EarlyA', 'LateA' ,'EarlyP', 'LateP'};

names={'BaseNoShoes','TMBaseShoes','SplitNeg','SplitPos','OGNimbus','Adaptation','OGpost-Adapt_{SS}','OGpost_{Early}','OGpost_{Late}','NIMPost_{Early}','NIMPost_{Late}'};

eps=defineEpochs(names,...
                {'OG base','TM base','Neg Short','Pos Short','NIM Base','NIM Adaptation','OG Post','OG Post','OG Post','NIM Post','NIM Post'},...
                [-40 -40 20 20 -40 -40 20 20 -40 20 -40],...
                [0,0,1,1,0,0,1,1,0,1,0],...
                [40,5,0,0,5,5,0,0,5,0,5],...
                nantype);