function [eps] = defineEpocNimbusShoesRegressor(nantype)

% names={'Base', 'EarlyA', 'LateA' ,'EarlyP', 'LateP'};

names={'TMBaseShoes','-\DeltaEMG_{on(+)}','SplitPos','\DeltaEMG_{on(-)}','OGNimbus','\DeltaEMG_{ss}','Adaptation','OGpost-Adapt_{SS}','OGpostEarly'};

eps=defineEpochs(names,...
                {'TM base','TM base','Pos Short','Neg Short',...
                'NIM Base','NIM Base','NIM Adaptation','OG Post','OG Post'},...
                [-40 -40 20 20 -40 -40  -40 20 20],...
                [0 0,1,1,0,0,0,1,0],...
                [5,5,0,0,5,5,5,0,5],...
                nantype);
            
   