function [eps] = defineEpochVR_OG(nantype)


names={'OGbase','TMBaseNOVR','SplitNeg','SplitPos','TMbase','Adaptation','OGpost-Adapt_{SS}','OGpost_{Early}','OGpost_{Late}','TMPost_{Early}','TMPost_{Late}'};

eps=defineEpochs(names,...
                {'OG base','TM tied 1','Neg Short','Pos Short','TM Base','Adaptation','OG post','OG post','OG post','TM post','TM post'},...
                [-40 -40 20 20 -40 -40 20 20 -40 20 -40],...
                [0,0,5,5,0,0,1,1,0,1,0],...
                [5,5,0,0,5,5,0,0,5,0,5],...
                nantype);